import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';
import { copyFileSync, mkdirSync, existsSync } from 'node:fs';

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const outdir = "build";

// Garante a pasta de saída e copia os arquivos estáticos que o Obsidian
// precisa junto do main.js (manifest e estilos).
function copyStaticFiles() {
	if (!existsSync(outdir)) {
		mkdirSync(outdir, { recursive: true });
	}
	copyFileSync("manifest.json", `${outdir}/manifest.json`);
	if (existsSync("styles.css")) {
		copyFileSync("styles.css", `${outdir}/styles.css`);
	}
}

// Recopia os estáticos a cada rebuild (importante no modo watch/dev).
const copyStaticPlugin = {
	name: "copy-static-files",
	setup(build) {
		build.onEnd(() => copyStaticFiles());
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: `${outdir}/main.js`,
	minify: prod,
	plugins: [copyStaticPlugin],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
